<a href="https://colab.research.google.com/github/ajaymanoj1515/Data_Analyst/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,3,10,9,5,7])
print(arr)

[ 1  3 10  9  5  7]


In [ ]:
arr2=np.matrix([[1,3,5,7],[2,4,6,8],])
print(arr2)

[[1 3 5 7]
 [2 4 6 8]]


In [ ]:
np.zeros(4)


array([0., 0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
print(arr)
s=np.sum(arr)
print("sum of array:",s)
me=np.mean(arr)
print("mean of array:",me)
ma=np.max(arr)
print("max of array:",ma)
mi=np.min(arr)
print("min of array:",mi)
so=np.sort(arr)
print("sorted array:",so)

[ 1  3 10  9  5  7]
sum of array: 35
mean of array: 5.833333333333333
max of array: 10
min of array: 1
sorted array: [ 1  3  5  7  9 10]
